name: Renovate

on:
  schedule: 
  - cron: "0 0 * * *"
  push:
    branches:
      main
  workflow_dispatch:
  issue_comment:
    types: [edited, created]
  issues:
    types: [edited]

env:
  POWERSHELL_CLI_TELEMETRY_OPTOUT: "1"
  POWERSHELL_TELEMETRY_OPTOUT: "1"
  POWERSHELL_UPDATECHECK: "Off"
  POWERSHELL_UPDATECHECK_OPTOUT: "1"
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_TELEMETRY_OPTOUT: "1"
  COMPlus_EnableDiagnostics: "0"

jobs:
  renovate:
    runs-on: windows-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write
    
    steps:
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: "18.x"
        
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: pwsh
      run: |
        "dir=$(npm config get cache --global)" >> ${env:GITHUB_OUTPUT}
        "npm show renovate version >> renovate-lock.txt"

    - uses: actions/cache@v3
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('renovate-lock.txt') }}

    - uses: actions/cache@v3
      with:
        path: "./.renovateCache"
        key: renovate-cache-${{ runner.os }}-${{ github.repository }}

    - name: Runs renovate against this repository. 
      run: |
        git config --global user.email 'bot@renovateapp.com'
        git config --global user.name 'Renovate Bot'
        npm install renovate
        npm exec -- renovate --platform=github --include-forks=true $env:REPOSITORY
      env:
        RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
        REPOSITORY:  ${{ github.repository }}
        RENOVATE_CACHE_DIR: "./.renovateCache"
